### ISSUE TITLE
Reducir el tamaño de los archivos generados por monolog en prod

### ISSUE THREAD

**Issue by inrumi** [MarinaVVsoftware/Novonautica#233]
Para reducir significativamente el tamaño de los logs en produccion, agregar esta linea a config
```yaml
#app/config/config_prod.yml

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            max_files: 7
        console:
            type: console
            process_psr_3_messages: false
```
